# Generated by Django 5.1 on 2024-08-14 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='archives',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
